# Generated by Django 4.2.19 on 2025-02-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
