# Generated by Django 4.2.19 on 2025-02-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalNotes',
            new_name='Notes',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
